### ISSUE TITLE
restgen crash

### ISSUE THREAD

**Issue by ted-strauss-K1** [alexferreira/restgen#7]
i followed the instructions to set up a simple rest with /user model+controller.
When i try it out by entering http://localhost:3000/users/ on my browser the server crashes with error below. I'm starting the server with `npm start` , not sure if that's the right way to start. And i'm running off a vagrant vm, but that shouldn't matter.

```
  ...
} has no method 'render'
    at module.exports.ErrorMapper.errMapper.default (/home/vagrant/resty/node_modules/restgen/lib/resterrors.js:61:11)
    at Object.module.exports.ErrorHandler [as handle] (/home/vagrant/resty/node_modules/restgen/lib/resterrors.js:73:3)
    at next (/home/vagrant/resty/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at resume (/home/vagrant/resty/node_modules/express/node_modules/connect/lib/middleware/static.js:60:7)
    at SendStream.error (/home/vagrant/resty/node_modules/express/node_modules/connect/lib/middleware/static.js:73:37)
    at SendStream.EventEmitter.emit (events.js:95:17)
    at SendStream.error (/home/vagrant/resty/node_modules/express/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/home/vagrant/resty/node_modules/express/node_modules/send/lib/send.js:248:48)
    at /home/vagrant/resty/node_modules/express/node_modules/send/lib/send.js:320:26
    at Object.oncomplete (fs.js:107:15)
 Mon, 08 Jul 2013 20:18:59 GMT GET / 7 ms 500

/home/vagrant/resty/node_modules/mongoose/lib/utils.js:419
        throw err;
              ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at /home/vagrant/resty/node_modules/restgen/lib/routes.js:12:27
    at Promise.<anonymous> (/home/vagrant/resty/node_modules/restgen/lib/basecontroller.js:25:9)
    at Promise.<anonymous> (/home/vagrant/resty/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/home/vagrant/resty/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.fulfill (/home/vagrant/resty/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
    at cb (/home/vagrant/resty/node_modules/mongoose/lib/query.js:1680:22)
    at /home/vagrant/resty/node_modules/mongoose/lib/utils.js:414:16
    at /home/vagrant/resty/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:158:16
    at commandHandler (/home/vagrant/resty/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:651:16)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by ted-strauss-K1** [comment]
Ok I see that i had the wrong syntax on the URL for querying. 
trial and error resolved it
